
import React, { forwardRef } from 'react';
import { Trip, DayPlan, Activity } from '../types';
import { MapPin, Clock, Wallet, Info } from 'lucide-react';

interface PrintLayoutProps {
    trip: Trip;
}

export const PrintLayout = forwardRef<HTMLDivElement, PrintLayoutProps>(({ trip }, ref) => {
    // Helper to calculate total cost
    const calculateTotalCost = () => {
        let total = 0;
        trip.days.forEach(day => {
            day.activities.forEach(act => total += (act.pricing?.basePrice || 0));
            day.travelSegments?.forEach(seg => total += (seg.transitFare || 0));
        });
        return total;
    };

    return (
        <div ref={ref} className="print-container p-8 font-sans text-gray-900 bg-white">
            {/* COVER PAGE */}
            <div className="min-h-screen flex flex-col items-center justify-center text-center break-after-page">
                <h1 className="text-5xl font-bold mb-4 text-indigo-900">{trip.title}</h1>
                <div className="text-xl text-gray-600 mb-8">
                    {trip.days.length} Days • {trip.days[0]?.city} Start
                </div>

                <div className="border-t border-b border-gray-200 py-8 px-12 w-full max-w-2xl">
                    <div className="grid grid-cols-3 gap-8 text-center">
                        <div>
                            <span className="block text-sm text-gray-500 uppercase tracking-wide">Total Days</span>
                            <span className="block text-3xl font-bold">{trip.days.length}</span>
                        </div>
                        <div>
                            <span className="block text-sm text-gray-500 uppercase tracking-wide">Est. Budget</span>
                            <span className="block text-3xl font-bold">¥{calculateTotalCost().toLocaleString()}</span>
                        </div>
                        <div>
                            <span className="block text-sm text-gray-500 uppercase tracking-wide">Stops</span>
                            <span className="block text-3xl font-bold">
                                {trip.days.reduce((acc, d) => acc + d.activities.length, 0)}
                            </span>
                        </div>
                    </div>
                </div>

                <div className="mt-12 text-sm text-gray-400">
                    Generated by Japan Travel Visualizer
                </div>
            </div>

            {/* DAYS */}
            {trip.days.map((day, index) => (
                <div key={day.id} className="break-before-page mb-8">
                    <div className="border-b-2 border-indigo-900 pb-4 mb-6 flex justify-between items-end">
                        <div>
                            <h2 className="text-3xl font-bold text-indigo-900">Day {index + 1}: {day.city}</h2>
                            <p className="text-gray-500 text-lg">{new Date(day.date).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</p>
                        </div>
                        {day.accommodation?.name && (
                            <div className="text-right text-sm">
                                <span className="block text-gray-400 uppercase text-xs">Accommodation</span>
                                <span className="font-semibold text-indigo-700">{day.accommodation.name}</span>
                            </div>
                        )}
                    </div>

                    {day.notes && (
                        <div className="mb-6 bg-yellow-50 p-4 rounded-lg border border-yellow-100 text-sm italic text-gray-700">
                            <strong>📝 Notes:</strong> {day.notes}
                        </div>
                    )}

                    <div className="space-y-6">
                        {day.activities.map((act) => (
                            <div key={act.id} className="break-inside-avoid flex gap-4 p-4 border border-gray-200 rounded-xl">
                                <div className="w-20 shrink-0 text-center pt-1">
                                    <div className="text-lg font-bold text-gray-900 leading-none">{act.startTime}</div>
                                    <div className="text-xs text-gray-400 mt-1">to {act.endTime}</div>
                                </div>

                                <div className="flex-1">
                                    <h3 className="text-lg font-bold text-gray-900 flex items-center gap-2">
                                        {act.name}
                                        {act.pricing && (
                                            <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${act.pricing.isFree ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'}`}>
                                                {act.pricing.isFree ? 'Free' : `¥${act.pricing.basePrice?.toLocaleString()}`}
                                            </span>
                                        )}
                                    </h3>
                                    <p className="text-sm text-gray-600 mb-2">{act.description}</p>

                                    <div className="flex items-center gap-4 text-xs text-gray-500">
                                        {act.location?.lat && (
                                            <span className="flex items-center gap-1">
                                                <MapPin className="w-3 h-3" />
                                                {act.location.lat.toFixed(4)}, {act.location.lng.toFixed(4)}
                                            </span>
                                        )}
                                        {act.durationReasoning && (
                                            <span className="flex items-center gap-1">
                                                <Clock className="w-3 h-3" />
                                                {act.durationReasoning}
                                            </span>
                                        )}
                                    </div>

                                    {/* Address/Notes if available would go here */}
                                </div>
                            </div>
                        ))}
                    </div>

                    {day.travelSegments && day.travelSegments.length > 0 && (
                        <div className="mt-6 pt-4 border-t border-gray-100 text-xs text-gray-400">
                            <strong>Estimated Travel Costs today:</strong> ¥{day.travelSegments.reduce((sum, s) => sum + (s.transitFare || 0), 0).toLocaleString()}
                        </div>
                    )}
                </div>
            ))}
        </div>
    );
});
